class Produkt:
    def __init__(self):
        self.kod_produktu = ''
        self.dostepny = False
        self.pozycja = 0
        self.kategoria = ''
        self.podkategoria1 = ''
        self.podkategoria2 = ''
        self.podkategoria3 = ''
        self.producent = ''
        self.promocja = False
        self.cena_detaliczna = 0
        self.cena_hurtowa = 0
        self.cena_minimalna = 0
        self.cena_euro_hurtowa = 0
        self.cena_euro_detaliczna = 0
        self.foto1 = ''
        self.foto2 = ''
        self.foto3 = ''
        self.foto4 = ''
        self.foto5 = ''
        self.foto6 = ''
        self.foto7 = ''
        self.foto8 = ''
        self.foto9 = ''
        self.foto10 = ''
        self.foto11 = ''
        self.foto12 = ''
        self.foto13 = ''
        self.foto14 = ''
        self.foto15 = ''
        self.foto16 = ''
        self.foto17 = ''
        self.foto18 = ''
        self.foto19 = ''
        self.foto20 = ''
        self.foto21 = ''
        self.foto22 = ''
        self.foto23 = ''
        self.foto24 = ''
        self.foto25 = ''
        self.nazwa = ''
        self.dopisek = ''
        self.video = ''
        self.opis = ''
        self.dane_tech = ''
        self.cechy = ''

    def update(self, newdata):
        for key, value in newdata.items():
            setattr(self, key, value)